# Generated by Django 5.1.15 on 2026-07-24 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('ct', 'CT scan'), ('pet', 'PET scan'), ('mri', 'MRI'), ('xray', 'X-ray'), ('lab', 'Laboratory'), ('other', 'Other')], default='other', max_length=16)),
                ('is_active', models.BooleanField(default=True, help_text='Inactive departments stop appearing on the order form.')),
                ('staff', models.ManyToManyField(blank=True, help_text='Department accounts that work this queue.', limit_choices_to={'role': 'department'}, related_name='departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.CharField(help_text="What to perform, for example 'CT head without contrast'.", max_length=120)),
                ('notes', models.TextField(blank=True, help_text='Clinical context for the department.')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent')], default='routine', max_length=16)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.department')),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.PROTECT, related_name='placed_orders', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='service_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['department', 'status', '-created_at'], name='orders_serv_departm_d3765c_idx'), models.Index(fields=['patient', '-created_at'], name='orders_serv_patient_ac7317_idx')],
            },
        ),
    ]
