# Generated by Django 5.1.15 on 2026-07-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Set by an administrator to decline the registration. Kept as a record instead of deleting the account.'),
        ),
    ]
