# Generated by Django 5.1.15 on 2026-07-25 19:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientdoctorassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presenting_complaint', models.TextField(blank=True, help_text='What the patient presented with, if known.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admitted_by', models.ForeignKey(limit_choices_to={'role': 'emergency'}, on_delete=django.db.models.deletion.PROTECT, related_name='emergency_admissions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.OneToOneField(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_intake', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
