# Generated by Django 5.1.15 on 2026-07-24 21:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('heart_rate', 'Heart rate'), ('bp_systolic', 'Blood pressure (systolic)'), ('bp_diastolic', 'Blood pressure (diastolic)'), ('blood_glucose', 'Blood glucose'), ('temperature', 'Body temperature'), ('spo2', 'Oxygen saturation'), ('weight', 'Weight')], max_length=32)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit', models.CharField(blank=True, max_length=16)),
                ('recorded_at', models.DateTimeField(help_text='When the device took the reading.')),
                ('source', models.CharField(choices=[('manual', 'Manual entry'), ('csv', 'CSV upload'), ('device', 'Device API')], default='manual', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='health_readings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-recorded_at',),
                'indexes': [models.Index(fields=['patient', 'metric', '-recorded_at'], name='records_hea_patient_d9952c_idx')],
            },
        ),
    ]
