# Generated by Django 5.1.15 on 2026-07-25 19:08

import apps.documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=apps.documents.storage.encrypted_storage, upload_to='documents/'),
        ),
    ]
